### ISSUE TITLE
Repeated results in search

### ISSUE THREAD

**Issue by bmaschio** [jolie/docs#14]
Hi @thesave 

I noticed a problem with the gitbook search facilities it gives always the same resuts

![image](https://user-images.githubusercontent.com/12083716/45828573-221cee00-bcf9-11e8-9444-0a7895f1c014.png)

Regards 
Balint

**Comment by thesave** [comment]
Hi @bmaschio,

Thanks for pointing this out.
I've been looking into this in the last few days but I couldn't find the source of the problem from "our" side. Moreover, it seems (stack overflow) that other people had the same problem with Gitbook at some point.
I'll try to contact the Gitbook admins to sort out the problem.

**Comment by thesave** [comment]
I have received a response from the Gitbook assistance on the issue.

Turns out, it is a general issue of Gitbook, which they are currently trying to pin down.

In the meantime they have reindexed the Jolie docs, which solved the problem for some terms (but e.g., searching for “protocol” still manifests the problem).

I’ll return on this as soon as I have some news.

**Comment by bmaschio** [comment]
@thesave 
We are the global bug finder
