### ISSUE TITLE
Time.ol Documentation 

### ISSUE THREAD

**Issue by bmaschio** [jolie/docs#15]
@thesave @jolie/developers 

Hey there how are I did find a few problems in decoding the information for the time.iol 
for example  

```
type ScheduleTimeOutRequest: int { 
    .message?: undefined
    .operation?: string
    .timeunit?: string
}
```
it is difficult to know what value to assign to timeunit, the only way I found to figure out what to use was to open the Jolie Project

Another example is **setNextTimeoutByDateTime( undefined )**

the actual code in the repository is 

```
public void setNextTimeoutByDateTime( Value request )
	{
		long waitTime = 0;
		try {
			synchronized( dateTimeFormat ) {
				Date date = dateTimeFormat.parse( request.strValue() );
				waitTime = date.getTime() - (new Date()).getTime();
			}
		} catch( ParseException e ) {}

```
In general the documentation kinds of assumes that the Jolie Programmer know how to read and program in Java 
Would be nice to insert one line of explanation on what the operation does so that the programmer does not have to "interpret" the functionality from the name
If you need a hand to add new information I am here just assign me the task

regards 
Balint

**Comment by fmontesi** [comment]
Would be useful to document/type it, indeed. I'm fine with you doing it of
course. @TheSave, @klag, can you join this discussion? I'm going to be
not-so-responsive during winter break. :-)

**Comment by thesave** [comment]
Sorry for the delay. Christmas hiatus - and by the way, Happy New Year :)
Totally agree in refining the interfaces of the standard library.

Regarding documentation, in the short term, I see a couple of solutions.

1. we point users to the related .iol file under the `include `folder in the Jolie repo in Github. Those files already contain comments to operations and types and we can increase/refine what's already there.

2. we modify the related gitbook pages with the additional information.

While solution 1 is pretty rough, the second is the most likely to produce overhead/misalignment. If we update an `include` file, then we need to manually update the documentation. Vice versa, when we will fully automatise the creation of the documentation (documenting operations and types) we will need to transport back the comments from the gitbook into the related `include` files.

For the time being, I'd go for solution 1 and provide an information panel at the beginning of the docs of the standard library saying that we are re-building it and, for the time being, more information can be found as comments to the operations and types in the related .iol file (linking to it for convenience).

What do you think about it @bmaschio, @fmontesi, @klag?

Looking a bit more to the future (and to the past), this conversation seems a reiteration of the one we had a couple of years ago [1] regarding the documentation of types. We had some proposals [2] but everything pretty much stopped [here](https://github.com/jolie/jolie/pull/91#issuecomment-254818134), probably due to personal constraints of the developer to proceed with the implementation.

To recap that conversation, we currently support the syntax `/**! ... */` to document (as in joliedoc) operations and we were looking for a syntax for types (i.e., to comment a type and its subnodes). 
IIRC, we settled with  `<//` to mean "this is a comment regarding the previous node".

To my understanding, to proceed with that, we need to parse `<//` comments and add that in the OLParser. Meanwhile, I am working on a new version of `joliedoc` as part of the standard library. The principle is to invoke the joliedoc functionality within a Jolie program, obtaining a Jolie value with all the structured information from joliedoc (ports, interfaces, operations, types). Then, joliedoc (the program we are used to call from the console to generate the standard library) would just be a Jolie program that calls joliedoc (the library), obtains the information, and uses that to render a visualization (HTML, Markdown, etc). In this way, we should become more flexible in outputting different formats (more so if we integrate in the process a template engine, e.g., [jtwig](http://jtwig.org/)). 

[1] https://github.com/jolie/jolie/pull/91
[2] https://github.com/jolie/jolie/pull/91#issuecomment-245213113

**Comment by bmaschio** [comment]
@thesave @fmontesi @klag
I have worked on point  1  on my branch [https://github.com/jolie/docs/blob/balint/documentation/jsl/Time.md](url)

In general, I agree we need to work on the joliedoc to auto-generate the documentation 
I have still some questions

- Is the documentation released when a new version of Jolie is released?
- How to include examples effectively
- How to include references to java stuff take the example of TimeUnit
- How to include depreciation or valid from version x.x.x

>  In this way, we should become more flexible in outputting different formats (more so if we integrate into the process a template engine, e.g., jtwig).

I like the idea  very much

I also found this project that allows to copy and paste `<code> `tags  [https://github.com/Mottie/GitHub-userscripts](URL) 
we could suggest in the documentation or follow their [https://github.com/Mottie/GitHub-userscripts/issues/66](URL)
thanks 
B

**Comment by klag** [comment]
Here my opinion:
1 - I agree that all the required information must be contained directly into the .iol file but I really do not like the idea to show the .iol file into the documentation.
2 - I agree with Saverio that is not a good solution because it is prone to misalignment and information loss


I think we should have to proceed with the implementation of comments for types as we defined in the previous discussions. 

@thesave I think you could use metajolie.iol, it already extracts all the information about a service returning it into a Jolie value. You just need to add a render for joliedoc.

Finally, I think we should structure a folder into this project https://github.com/jolie/examples with all the examples for each javaservice. They could be automatically attached to the online documentation. We just need to define some basic rules for writing these examples together with the comments in order to be correctly shown into gitbook.

**Comment by bmaschio** [comment]
@thesave @klag @fmontesi 
Let's be pragmatic the development of the new cool tool joliedoc is going to require a certain effort in time of development. I suggest that we correct by hand the standard services documentation and at least produce an effective format, then we develop the tool based on the format.

what you think
Balint

**Comment by thesave** [comment]
I published a project [1] that compiles the Jolie Standard Library at as .md files for Gitbook.

By default, the tool looks for the `include` files in your JOLIE_HOME folder, but you can change [this line](https://github.com/thesave/build_jsl/blob/e94ca17472c4eab929f6558256cd2ef0b6f5d12d/build_jsl.ol#L48) to make it point to e.g., the `dist` folder of your local Jolie repository. Then you can comment those `include` files and see how they might look like in the Gitbook documentation.

Now, as @klag suggested, we just need to enhance the script in [1] to look into repository [2] and include the examples related to a given `include` file into its documentation page.

Who's up for that? :)

[1] https://github.com/thesave/build_jsl
[2] https://github.com/jolie/examples

**Comment by thesave** [comment]
Hi, I polished a bit the project at [1] so now it outputs the JSL as well-formatted .md files for Gitbook.
I already committed the change on Gitbook, so if you look into the docs and find something strange, please report it here, so I fix it ASAP.
I also added some nice shortcuts in the docs, so now when you look into the docs of some library you can quickly copy-paste the code for: 

- including the library
- calling an operation
- installing a handler for a fault

@fmontesi the project can be also integrated into an automatic script that updates the JSL each time we release a new version of Jolie. 
It is sufficient to clone the repository, run the `install_dependencies.ol` file, and then run the command `jolie build_jsl.ol .md markdown_template.liquid path/to/docs/repo`.

[1] https://github.com/thesave/build_jsl
