### ISSUE TITLE
Syntax of allowed interface/operations inside outputPort / inputPort

### ISSUE THREAD

**Issue by SuperMauro1966** [jolie/docs#55]
Inside the example 
https://github.com/jolie/jocker/blob/master/ExampleOrchestrator/clientHello.ol

for joker

we could find a legacy syntax (???) for the interfaces in outputPort:

...

outputPort p {
	...
	RequestResponse: get
}

main {
  get@p()(response);
  println@Console(response)()
}

Shall we update the documentation about the syntax of outputPort/inputPort or modify the example and remove from the parser the old syntax?

**Comment by mwallnoefer** [comment]
Also mentioning @klag, the original author of the code.

The `get` call does not contain the input-output-type which is basically the same as `RequestResponse: get(undefined)(undefined)`. However also this old syntax continues to be technically valid.

That said this example isn't part of the _docs_ project so I close this issue here. Feel free to provide a patch (PR) for the _jocker_ subproject if you really want to see it changed.
